<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.1.2.344
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Indsendelse af Opret lejer formular',
	'heading' => 'Ny formularindsendelse',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Markeret',
		'checkbox_unchecked' => 'Ikke markeret',
		'submitted_from' => 'Formular indsendt fra website: %s',
		'submitted_by' => 'Besøgendes IP-adresse: %s',
		'too_many_submissions' => 'For mange nylige indsendelser fra denne IP',
		'failed_to_send_email' => 'Kunne ikke sende e-mail',
		'invalid_reCAPTCHA_private_key' => 'Ugyldig privat reCAPTCHA-nøgle.',
		'invalid_field_type' => 'Ukendt felttype \'%s\'.',
		'invalid_form_config' => 'Feltet \'%s\' har en ugyldig konfiguration.',
		'unknown_method' => 'Ukendt serveranmodningsmetode'
	),
	'email' => array(
		'from' => 'info@jobautomaten.dk',
		'to' => 'info@jobautomaten.dk'
	),
	'fields' => array(
		'Email' => array(
			'order' => 12,
			'type' => 'email',
			'label' => 'E-mail',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'E-mail\' er påkrævet.',
				'format' => 'Feltet \'E-mail\' har en ugyldig e-mailadresse.'
			)
		),
		'custom_U5944' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Tidligere arbejde',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Tidligere arbejde\' er påkrævet.'
			)
		),
		'custom_U5922' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Særlige forhold?',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Særlige forhold?\' er påkrævet.'
			)
		),
		'custom_U5910' => array(
			'order' => 13,
			'type' => 'string',
			'label' => 'Profiltekst',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Profiltekst\' er påkrævet.'
			)
		),
		'custom_U5965' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Erhvervserfaring',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Erhvervserfaring\' er påkrævet.'
			)
		),
		'custom_U5940' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Adresse',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Adresse\' er påkrævet.'
			)
		),
		'custom_U6011' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Telefon',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Telefon\' er påkrævet.'
			)
		),
		'custom_U26210' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Uddannelsesniveau',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Uddannelsesniveau\' er påkrævet.'
			)
		),
		'custom_U26036' => array(
			'order' => 1,
			'type' => 'checkboxgroup',
			'label' => 'I hvilken regioner?',
			'required' => true,
			'optionItems' => array(
				'Københavnsområdet',
				'Region Sjælland',
				'Midtjylland',
				'Skåne',
				'Fyn',
				'Sydjylland',
				'Andet',
				'Nordjylland',
				'Bornholm'
			),
			'errors' => array(
				'required' => 'Feltet \'I hvilken regioner?\' er påkrævet.',
				'format' => 'Feltet \'I hvilken regioner?\' har en ugyldig værdi.'
			)
		),
		'custom_U5956' => array(
			'order' => 6,
			'type' => 'checkboxgroup',
			'label' => 'Køn',
			'required' => false,
			'optionItems' => array(
				'Mand',
				'Kvinde'
			),
			'errors' => array(
				'format' => 'Feltet \'Køn\' har en ugyldig værdi.'
			)
		),
		'custom_U5978' => array(
			'order' => 2,
			'type' => 'checkboxgroup',
			'label' => 'Hvad vil du gerne arbejde med?',
			'required' => false,
			'optionItems' => array(
				'Informationsteknologi',
				'Ingeniør og teknik',
				'Ledelse og personale',
				'Handel og service',
				'Industri og håndværk',
				'Salg og kommunikation',
				'Undervisning',
				'Kontor og økonomi',
				'Social og sundhed',
				'Andet'
			),
			'errors' => array(
				'format' => 'Feltet \'Hvad vil du gerne arbejde med?\' har en ugyldig værdi.'
			)
		),
		'custom_U6314' => array(
			'order' => 3,
			'type' => 'checkboxgroup',
			'label' => 'Jobtype',
			'required' => true,
			'optionItems' => array(
				'Fuldtid',
				'Praktik',
				'Fleksjob',
				'Deltid',
				'Pensionist job',
				'Løntilskud',
				'Vikar',
				'Elevplads/læreplads',
				'Besøgsven',
				'Frivillig'
			),
			'errors' => array(
				'required' => 'Feltet \'Jobtype\' er påkrævet.',
				'format' => 'Feltet \'Jobtype\' har en ugyldig værdi.'
			)
		),
		'custom_U6419' => array(
			'order' => 5,
			'type' => 'checkboxgroup',
			'label' => 'Andet',
			'required' => true,
			'optionItems' => array(
				'Kørekort',
				'Stort kørekort',
				'Taler dansk'
			),
			'errors' => array(
				'required' => 'Feltet \'Andet\' er påkrævet.',
				'format' => 'Feltet \'Andet\' har en ugyldig værdi.'
			)
		)
	)
);

process_form($form);
?>
