<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.1.2.344
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Indsendelse af Home kopi formular',
	'heading' => 'Ny formularindsendelse',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Markeret',
		'checkbox_unchecked' => 'Ikke markeret',
		'submitted_from' => 'Formular indsendt fra website: %s',
		'submitted_by' => 'Besøgendes IP-adresse: %s',
		'too_many_submissions' => 'For mange nylige indsendelser fra denne IP',
		'failed_to_send_email' => 'Kunne ikke sende e-mail',
		'invalid_reCAPTCHA_private_key' => 'Ugyldig privat reCAPTCHA-nøgle.',
		'invalid_field_type' => 'Ukendt felttype \'%s\'.',
		'invalid_form_config' => 'Feltet \'%s\' har en ugyldig konfiguration.',
		'unknown_method' => 'Ukendt serveranmodningsmetode'
	),
	'email' => array(
		'from' => 'info@jobautomaten.dk',
		'to' => 'info@jobautomaten.dk'
	),
	'fields' => array(
		'Email' => array(
			'order' => 11,
			'type' => 'email',
			'label' => 'Telefon',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Telefon\' er påkrævet.',
				'format' => 'Feltet \'Telefon\' har en ugyldig e-mailadresse.'
			)
		),
		'custom_U18413' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Hvor',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Hvor\' er påkrævet.'
			)
		),
		'custom_U18436' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Jobtype',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Jobtype\' er påkrævet.'
			)
		),
		'custom_U18425' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Arbejdstid',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Arbejdstid\' er påkrævet.'
			)
		),
		'custom_U18454' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Dato for start',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Dato for start\' er påkrævet.'
			)
		),
		'custom_U18470' => array(
			'order' => 13,
			'type' => 'string',
			'label' => 'Annoncetekst',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Annoncetekst\' er påkrævet.'
			)
		),
		'custom_U18417' => array(
			'order' => 6,
			'type' => 'checkbox',
			'label' => 'Kørekort',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Kørekort\' er påkrævet.'
			)
		),
		'custom_U18449' => array(
			'order' => 5,
			'type' => 'checkbox',
			'label' => 'Fysisk krævende job',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Fysisk krævende job\' er påkrævet.'
			)
		),
		'custom_U18462' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Name\' er påkrævet.'
			)
		),
		'custom_U18432' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Adresse',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Adresse\' er påkrævet.'
			)
		),
		'custom_U18458' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Stilling',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Stilling\' er påkrævet.'
			)
		),
		'custom_U18466' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Mail',
			'required' => true,
			'errors' => array(
				'required' => 'Feltet \'Mail\' er påkrævet.'
			)
		),
		'custom_U18440' => array(
			'order' => 7,
			'type' => 'checkboxgroup',
			'label' => 'Dansk sproglighed',
			'required' => false,
			'optionItems' => array(
				'Ja',
				'Nej, er ikke vigtigt'
			),
			'errors' => array(
				'format' => 'Feltet \'Dansk sproglighed\' har en ugyldig værdi.'
			)
		)
	)
);

process_form($form);
?>
