<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.1.2.344
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Indsendelse af Søg formular',
	'heading' => 'Ny formularindsendelse',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Markeret',
		'checkbox_unchecked' => 'Ikke markeret',
		'submitted_from' => 'Formular indsendt fra website: %s',
		'submitted_by' => 'Besøgendes IP-adresse: %s',
		'too_many_submissions' => 'For mange nylige indsendelser fra denne IP',
		'failed_to_send_email' => 'Kunne ikke sende e-mail',
		'invalid_reCAPTCHA_private_key' => 'Ugyldig privat reCAPTCHA-nøgle.',
		'invalid_field_type' => 'Ukendt felttype \'%s\'.',
		'invalid_form_config' => 'Feltet \'%s\' har en ugyldig konfiguration.',
		'unknown_method' => 'Ukendt serveranmodningsmetode'
	),
	'email' => array(
		'from' => 'feel@live.dk',
		'to' => 'feel@live.dk'
	),
	'fields' => array(
		'custom_U24708' => array(
			'order' => 1,
			'type' => 'checkboxgroup',
			'label' => 'Afkrydsningsfeltgruppe',
			'required' => true,
			'optionItems' => array(
				'Fuldtid',
				'Deltid',
				'Pensionist job',
				'Praktik',
				'Fleksjob',
				'Løntilskud',
				'Københavnsområdet',
				'Region Sjælland',
				'Frivillig',
				'Andet',
				'Sydjylland',
				'Vikar',
				'Fyn',
				'Midtjylland',
				'Elevplads/læreplads',
				'Nordjylland',
				'Bornholm',
				'Besøgsven'
			),
			'errors' => array(
				'required' => 'Feltet \'Afkrydsningsfeltgruppe\' er påkrævet.',
				'format' => 'Feltet \'Afkrydsningsfeltgruppe\' har en ugyldig værdi.'
			)
		)
	)
);

process_form($form);
?>
